### ISSUE TITLE
[EPIC] Design energy-consumption tests

### ISSUE THREAD

**Issue by nikimanoledaki** [nikimanoledaki/gitops-energy-usage#1]
## `date-setter` Go app
- [x] Go server that takes current date, sets it as a `deployment.yaml` metadata name, and marshals it into YAML

## GitOps arch
- [x] Script to bootstrap Flux to watch this repo's `deployment.yaml`
- [x] https://github.com/nikimanoledaki/gitops-energy-usage/issues/4

## Snowflake arch
- [ ] #9

## Setup energy metrics
- [x] https://github.com/nikimanoledaki/gitops-energy-usage/issues/6

## Cron job
- [ ] Schedule job that runs `date-setter` app and should trigger Flux reconciliation & GitHub Action workflow
